### ISSUE TITLE
block_io.rb:140:in `rescue in block in api_call': Unknown error occurred. Please report this. (Exception)

### ISSUE THREAD

**Issue by damiong28** [BlockIo/gem-block-io#5]
I occasionally (rarely) get this exception when making API calls to check a wallet balance.

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/block_io-1.0.8/lib/block_io.rb:140:in `re
scue in block in api_call': Unknown error occurred. Please report this. (Excepti
on)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/block_io-1.0.8/lib/block_io.
rb:136:in `block in api_call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/co
nnection_pool.rb:64:in `block (2 levels) in with'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/co
nnection_pool.rb:63:in `handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/co
nnection_pool.rb:63:in `block in with'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/co
nnection_pool.rb:60:in `handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/co
nnection_pool.rb:60:in `with'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/block_io-1.0.8/lib/block_io.
rb:131:in `api_call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/block_io-1.0.8/lib/block_io.
rb:47:in `method_missing'
        from block_balance.rb:37:in `block (2 levels) in <main>'
        from block_balance.rb:31:in `each_line'
        from block_balance.rb:31:in `block in <main>'
        from block_balance.rb:30:in `open'
        from block_balance.rb:30:in `<main>'
```

**Comment by damiong28** [comment]
I modified the error message to return the response, here's part of what I got back the next time I got it:

...
@body="<h2>This website is under heavy load (queue full)</h2><p>We're sor
ry, too many people are accessing this website at the same time. We're working o
n this problem. Please try again later.</p>"
...

**Comment by doersf** [comment]
Yes, this is due to server connectivity issues. Relates to overall stability of the servers, not related to the SDK.
